export const GET_MENUS = 'GET_MENUS'
export const CLICK_MENU = 'CLICK_MENU'
export const GET_USERINFO = 'GET_USERINFO'
export const TOGGLE_SIDE = 'TOGGLE_SIDE'
export const ADD_TAB = 'ADD_TAB'
export const REMOVE_TAB ='REMOVE_TAB'
export const CHANGE_TAB ='CHANGE_TAB'
